const lang = ['en', 'ru', 'be'];
const controlsLocale = {
  en: ['Search', 'Search city or ZIP', 'Latitude: ', 'Longintude: ', 'Feels like: ', 'Wind: ', ' m/s', 'Humidity: '],
  ru: [
    'Найти',
    'Найти по названию/индексу',
    'Широта: ',
    'Долгота: ',
    'Ощущается как ',
    'Ветер: ',
    ' м/с',
    'Влажность: ',
  ],
  be: [
    'Знайсці',
    'Пошук горад/паштовы індэкс',
    'Шырата: ',
    'Даўгата: ',
    'Адчуваецца як ',
    'Вецер: ',
    ' м/с',
    'Вільготнасць: ',
  ],
};

const weekDayArr = {
  en: [
    'Sun',
    'Mon',
    'Tue',
    'Wed',
    'Thu',
    'Fri',
    'Sat',
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thusday',
    'Friday',
    'Saturday',
  ],
  ru: [
    'Вс',
    'Пн',
    'Вт',
    'Ср',
    'Чт',
    'Пт',
    'Сб',
    'Воскресенье',
    'Понедельник',
    'Вторник',
    'Среда',
    'Четверг',
    'Пятница',
    'Суббота',
  ],
  be: [
    'Няд',
    'Пнд',
    'Аўт',
    'Сер',
    'Чцв',
    'Пят',
    'Суб',
    'Нядзеля',
    'Панядзелак',
    'Аўторак',
    'Серада',
    'Чацьвер',
    'Пятніца',
    'Субота',
  ],
};

const monthArr = {
  en: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  ru: [
    'Январь',
    'Февраль',
    'Март',
    'Апрель',
    'Май',
    'Июнь',
    'Июль',
    'Август',
    'Сентябрь',
    'Октябрь',
    'Ноябрь',
    'Декабрь',
  ],
  be: [
    'Студзень',
    'Люты',
    'Сакавiк',
    'Красавiк',
    'Май',
    'Червень',
    'Лiпень',
    'Жнiвень',
    'Верасень',
    'Кастрычнiк',
    'Лiстапад',
    'Снежань',
  ],
};

const weatherIcons = new Map([
  ['clear-day', 'clear-day'],
  ['clear-night', 'clear-night'],
  ['rain', 'rain'],
  ['snow', 'snow'],
  ['sleet', 'sleet'],
  ['wind', 'wind'],
  ['fog', 'fog'],
  ['cloudy', 'cloudy'],
  ['partly-cloudy-day', 'partly-cloudy-day'],
  ['partly-cloudy-night', 'partly-cloudy-night'],
]);

const errorMsg = {
  en: [
    'Enter valid name of city/settlement.',
    'Geolocation is not supported by this browser.',
    "Weather data hasn't been loaded",
    'The coordinates were not determined. Refresh page.',
    'The map was not loaded.',
    'Something goes wrong. Connect to support',
    'The background image was not loaded.',
    'Speak again',
    "You're pushing too fast. Wait for the microphone to be ready",
  ],
  ru: [
    'Введите правильное название населенного пункта.',
    'Геолокация не поддерживается этим браузером.',
    'Погодные данные не загружены',
    'Координаты не были определены. Обновить страницу.',
    'Карта не была загружена.',
    'Что-то пошло не так. Напишите в поддержку',
    'Фоновое изображение не было загружено.',
    'Повторите название населенного пункта',
    'Вы слишком быстро нажимаете. Дождитесь, когда микрофон будет готов',
  ],
  be: [
    'Калі ласка, увядзіце правільнае назва населенага пункта.',
    'Геолокация не падтрымліваецца гэтым браўзэрам.',
    'Пагодныя дадзеныя не загружаныя',
    'Каардынаты не былі вызначаныя. Абнавіць старонку',
    'Карта не была загружаная.',
    'Нешта ідзе не так. Падлучэнне да падтрымкі.',
    'Фонавы малюнак не было загружана.',
    'Паўтарыце назва населенага пункта',
    'Вы занадта хутка націскаеце. Дачакайцеся, калі мікрафон будзе гатовы',
  ],
};

export { weekDayArr, monthArr, lang, controlsLocale, weatherIcons, errorMsg };
